models/Gives.php
<?php

namespace app\models;

use Yii;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "gives".
 *
 * @property int $id
 * @property int $bloger_id
 * @property int $bloger_id_sec
 * @property int $count_sub
 * @property string $date_start
 * @property string $date_end
 * @property int $count_seats
 * @property int $cost
 * @property int $title
 * @property int $is_main
 * @property boolean $is_hot
 * @property boolean $is_top
 * @property boolean $is_on
 * @property int $status
 * @property int $plus_subscriber
 * @property string $presents
 * @property string $video_link
 * @property string $image
 * @property string $subscribes_in
 * @property string $sort
 * @property float $all_cost
 * @property GiveHasUser[] $giveHasUsers
 * @property GiveHasUser[] $getGiveHasUsersCustom
 * @property Blogers $bloger
 */
class Gives extends \yii\db\ActiveRecord
{
    const STATUS_NEW = 1;
    const STATUS_END = 2;

    /**
     * {@inheritdoc}
     */
    public function statuses()
    {
        return [
            self::STATUS_NEW => 'Новый',
            self::STATUS_END => 'Закончился',
        ];
    }

    public static function tableName()
    {
        return 'gives';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['bloger_id', 'bloger_id_sec', 'count_sub', 'count_seats', 'status', 'plus_subscriber', 'sort'], 'integer'],
            [['cost', 'all_cost', 'image', 'is_hot','is_top','is_on'], 'safe'],
            [['date_start', 'date_end', 'title', 'video_link', 'presents', 'subscribes_in'], 'safe'],
            [['is_main'], 'boolean'],
            [['bloger_id'], 'exist', 'skipOnError' => true, 'targetClass' => Blogers::className(), 'targetAttribute' => ['bloger_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'bloger_id' => 'Блогер',
            'bloger_id_sec' => 'Блогер_2',
            'count_sub' => 'Подписчиков пришло',
            'date_start' => 'Дата начала',
            'date_end' => 'Дата окночания',
            'count_seats' => 'К-тво мест',
            'cost' => 'Стоимость подписчика',
            'title' => 'Название',
            'is_star' => 'В топе',
            'video_link' => 'Ссылка на видео',
            'presents' => 'Подарки',
            'subscribes_in' => 'Приход подписчиков',
            'status' => 'Статус',
            'is_main' => 'На главную',
            'plus_subscriber' => 'Накрутка(Это число + реальные подписчики)',
            'all_cost' => 'Полная цена',
            'image' => 'Превью видео',
            'sort' => 'Сортировка',
            'is_hot' => 'Горячий гив',
            'is_top' => 'Топовый гив',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGiveHasUsers()
    {
        return $this->hasMany(GiveHasUser::className(), ['give_id' => 'id']);
    }

    public function getGiveHasUsersCustom()
    {
        return $this->hasMany(GiveHasUser::className(), ['give_id' => 'id'])->andWhere(['user_id' => Yii::$app->user->identity->id]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBloger()
    {
        return $this->hasOne(Blogers::className(), ['id' => 'bloger_id']);
    }

    public function getBlogerSec()
    {
        return $this->hasOne(Blogers::className(), ['id' => 'bloger_id_sec']);
    }
}

controllers/GivesController.php
<?php

namespace app\controllers;

use app\models\Blogers;
use app\models\User;
use Yii;
use app\models\Gives;
use app\models\search\GivesSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * GivesController implements the CRUD actions for Gives model.
 */
class GivesController extends Controller
{

    /**
     * Lists all Gives models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GivesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->identity->role != User::ROLE_ADMIN) {
            return $this->redirect(['/']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays a single Gives model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Gives model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Gives();

        if ($model->load(Yii::$app->request->post())) {
            $model->status = Gives::STATUS_NEW;
            if ($file = UploadedFile::getInstance($model, 'image')) {
                $dir = Yii::getAlias('@webroot/img/');
                $fname = uniqid("", true) . '.' . $file->extension;
                $model->image = $fname;
                $file->saveAs($dir . $fname);
            }
            $give = Gives::find()->max('sort');
            if ($give) {
                $model->sort = $give + 1;
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            };
        }

        return $this->render('create', [
            'model' => $model,
            'blogers' => $this->getBlogers()
        ]);
    }

    protected function getBlogers()
    {
        return ArrayHelper::map(Blogers::find()->all(), 'id', 'name');
    }

    /**
     * Updates an existing Gives model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $image = $model->image;
        if ($model->load(Yii::$app->request->post())) {
            if ($file = UploadedFile::getInstance($model, 'image')) {
                $dir = Yii::getAlias('@webroot/img/');
                $fname = uniqid("", true) . '.' . $file->extension;
                $model->image = $fname;
                $file->saveAs($dir . $fname);
            } else {
                $model->image = $image;
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'blogers' => $this->getBlogers()
        ]);
    }

    public function actionNew($id)
    {
        $model = $this->findModel($id);
        $model->status = Gives::STATUS_NEW;
        $model->save(false);

        return $this->redirect('/gives/index');
    }

    public function actionFinish($id)
    {
        $model = $this->findModel($id);
        $model->status = Gives::STATUS_END;
        $model->save(false);
        return $this->redirect('/gives/index');
    }

    /**
     * Deletes an existing Gives model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionPayOnOff($id)
    {
        $model = $this->findModel($id);
        if ($model->is_on) {
            $model->is_on = 0;
            Yii::$app->session->setFlash('success', 'Оплаты выкл.');
        } else {
            $model->is_on = 1;
            Yii::$app->session->setFlash('success', 'Оплаты вкл.');
        }
        $model->save(false);
        return $this->redirect(['index']);
    }

    /**
     * Finds the Gives model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Gives the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Gives::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/gives/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Gives */
/* @var $form yii\widgets\ActiveForm */
/* @var $blogers \app\models\Blogers[] */

?>

<div class="gives-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'bloger_id')->widget(\kartik\select2\Select2::classname(), [
        'data' => $blogers,
        'language' => 'ru',
        'options' => ['placeholder' => 'Выбрать блогера'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>
    <?= $form->field($model, 'subscribes_in')->textInput() ?>
    <?= $form->field($model, 'cost')->textInput() ?>
    <?php
    if (!$model->isNewRecord) {
        echo $form->field($model, 'sort')->textInput();
    }
    if ($model->image) {
        echo Html::img('/img/' . $model->image, ['class' => 'img_profile', 'style' => 'width: 200px']);
    }
    ?>

    <?= $form->field($model, 'date_start')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/gives/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\GivesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gives-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'bloger_id') ?>

    <?= $form->field($model, 'count_sub') ?>

    <?= $form->field($model, 'date_start') ?>

    <?= $form->field($model, 'date_end') ?>

    <?php // echo $form->field($model, 'count_seats') ?>

    <?php // echo $form->field($model, 'cost') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/gives/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Gives */
/* @var $blogers \app\models\Blogers[] */

$this->title = Yii::t('app', 'Создание гива');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Гивы'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gives-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'blogers' => $blogers
    ]) ?>

</div>

views/gives/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\GivesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Гивы');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gives-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Создать гив'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'bloger_id',
                'value' => function (\app\models\Gives $model) {
                    return $model->bloger->name;
                }
            ],
            [
                'attribute' => 'status',
                'value' => function (\app\models\Gives $model) {
                    return $model->statuses()[$model->status];
                }
            ],
            'title',
            'video_link',
            'count_sub',
            'presents',
            'subscribes_in',
            'plus_subscriber',
            'date_start',
            'date_end',
            'count_seats',
            'cost',
            'sort',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete} {view} {new} {finish} {payment}',
                'buttons' => [
                    'update' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-pencil"></i>', \yii\helpers\Url::to(['/gives/update', 'id' => $model->id]), [
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-trash"></i>', \yii\helpers\Url::to(['/gives/delete', 'id' => $model->id]), [
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]);
                    },
                    'view' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-eye-open"></i>', \yii\helpers\Url::to(['/gives/view', 'id' => $model->id]), [
                        ]);
                    },
                    'new' => function ($url, $model) {
                        return Html::a('<i title="Новый" class="glyphicon glyphicon-ok"></i>', \yii\helpers\Url::to(['/gives/new', 'id' => $model->id]), [
                        ]);
                    },
                    'finish' => function ($url, $model) {
                        return Html::a('<i title="Закончить" class="glyphicon glyphicon-remove"></i>', \yii\helpers\Url::to(['/gives/finish', 'id' => $model->id]), [
                        ]);
                    },
                    'payment' => function ($url, $model) {
                        return Html::a('<i title="Вкл/выкл Оплату" class="glyphicon glyphicon-adjust"></i>', \yii\helpers\Url::to(['/gives/pay-on-off', 'id' => $model->id]), [
                        ]);
                    }
                ]
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/gives/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Gives */
/* @var $blogers \app\models\Blogers[] */

$this->title = Yii::t('app', 'Редактирование гива  {name}', [
    'name' => $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Гивы'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Редактирование');
?>
<div class="gives-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'blogers' => $blogers
        ,
    ]) ?>

</div>

views/gives/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Gives */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Gives'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="gives-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'bloger_id',
                'value' => function (\app\models\Gives $model) {
                    return $model->bloger->instagram_name;
                }
            ],
            'count_sub',
            'date_start',
            'date_end',
            'count_seats',
            'cost',
            'sort',
        ],
    ]) ?>

    <?php
    $dataProvider = new \yii\data\ActiveDataProvider([
        'query' => $model->getGiveHasUsers(),
        'pagination' => [
            'pageSize' => 20,
        ],
    ]);

    ?>
    <div><h2>Участвуют в данном Гиве</h2></div>
    <?= \yii\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'user.first_name',
            'user.last_name',
            'user.email',
            'user.instagram_ak',
            'user.phone',

            //  ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>