models/User.php
<?php

namespace app\models;

use app\components\MyUrlManager;
use DeepCopy\f006\A;
use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\VarDumper;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property integer $email_status
 * @property string $email
 * @property string $password
 * @property string $first_name
 * @property string $last_name
 * @property string $patronymic
 * @property integer $role
 * @property integer $telegramm_see
 * @property string $promo
 * @property string $instagram_ak
 * @property string $target
 * @property string $status
 * @property string $phone
 * @property string $invoiceId
 * @property PaymentLer $payment
 * @property GiveHasUser[] $giveHasUsersCustom
 */
class User extends ActiveRecord implements IdentityInterface
{
    const ROLE_USER = 0;
    const ROLE_ADMIN = 1;
    const SCENARIO_CHANGE_PASSWORD_USER = 'change_password_user';

    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    public $orig_password;
    public $new_password;
    public $password1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_CHANGE_PASSWORD_USER] = ['orig_password', 'new_password', 'password1'];
        return $scenarios;
    }

    /**
     * @inheritdoc
     */

    public function rules()
    {
        return [
            [['email', 'first_name', 'last_name', 'patronymic', 'phone', 'instagram_ak', 'target'], 'safe'],
            [['target', 'instagram_ak', 'status', 'password', 'invoiceId', 'email_status', 'refferer_link', 'telegramm_see', 'login_date'], 'safe'],
            [['email'], 'email'],
            [['email'], 'unique', 'message' => '{attribute} уже занят!'],
            ['password1', 'compare',
                'compareAttribute' => 'new_password',
                'on' => self::SCENARIO_CHANGE_PASSWORD_USER,
                'message' => 'Пароли не совпадают'
            ],
            ['orig_password', 'myCompare', 'on' => self::SCENARIO_CHANGE_PASSWORD_USER],
            [['orig_password', 'new_password', 'password1'], 'required', 'on' => self::SCENARIO_CHANGE_PASSWORD_USER]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'password' => 'Пароль',
            'first_name' => ' Имя',
            'last_name' => 'Фамилия',
            'patronymic' => 'Отчество',
            'status' => 'Статус',
            'target' => 'Цель участия',
            'orig_password' => 'Старый пароль',
            'new_password' => 'Новый пароль',
            'password1' => 'Новый пароль',
            'phone' => 'Телефон',
            'login_status' => 'Статус авторизации',
            'login_date' => 'Дата авторизации',
            'refferer_link' => 'Переход по ссылке',
            'email_status' => 'Получил ли письмо клиент',
            'telegramm_see' => 'Видил ли попап',
        ];
    }

    /**
     * Finds an identity by the given ID.
     * @param string|integer $id the ID to be looked for
     * @return IdentityInterface the identity object that matches the given ID.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentity($id)
    {
        return User::findOne(['id' => $id]);
    }

    /**
     * Finds an identity by the given token.
     * @param mixed $token the token to be looked for
     * @param mixed $type the type of the token. The value of this parameter depends on the implementation.
     * For example, [[\yii\filters\auth\HttpBearerAuth]] will set this parameter to be `yii\filters\auth\HttpBearerAuth`.
     * @return IdentityInterface the identity object that matches the given token.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return null;
    }

    /**
     * Returns an ID that can uniquely identify a user identity.
     * @return string|integer an ID that uniquely identifies a user identity.
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns a key that can be used to check the validity of a given identity ID.
     *
     * The key should be unique for each individual user, and should be persistent
     * so that it can be used to check the validity of the user identity.
     *
     * The space of such keys should be big enough to defeat potential identity attacks.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @return string a key that is used to check the validity of a given identity ID.
     * @see validateAuthKey()
     */
    public function getAuthKey()
    {
        return $this->authKey;

    }

    /**
     * Validates the given auth key.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @param string $authKey the given auth key
     * @return boolean whether the given auth key is valid.
     * @see getAuthKey()
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    public function myCompare($attribute, $params)
    {
        if ($this->$attribute != $this->password) {
            $this->addError($attribute, 'Старый пароль не совпадает');
        }
    }

    public function updatePassword($new_password)
    {
        $this->password = $new_password;
    }

    public function getUserName()
    {
        if ($this->first_name && $this->last_name) {
            return $this->first_name . ' ' . $this->last_name;
        }
        return $this->email;
    }

    public function getUserFIO()
    {
        return $this->first_name . ' ' . $this->last_name . ' ' . $this->patronymic;
    }

    public static function findByEmail($email)
    {
        return User::findOne(['email' => $email]);
    }

    public function login()
    {
        return Yii::$app->user->login($this);
    }

    public function validatePassword($password)
    {
        return $this->password === $password;
    }

    public function getStatusString()
    {

        $statuses = self::getStatusesArray();

        if (isset($statuses[$this->status])) {

            return $statuses[$this->status];
        }

        return 'Ожидание';
    }

    public static function getStatusesArray()
    {
        return [
            self::STATUS_ACTIVE => 'Консультация',
            self::STATUS_INACTIVE => 'Не оплачен',
        ];
    }

    public function getLabelCssClassByStatus()
    {
        return $this->status == self::STATUS_ACTIVE ? 'label label-primary' : 'label label-danger';
    }

    public function getPayment()
    {
        return $this->hasOne(PaymentLer::class, ['user_id' => 'id']);
    }

    public function getGiveHasUsersCustom($give_id)
    {
        return $this->hasMany(GiveHasUser::className(), ['user_id' => 'id'])->andWhere(['give_id' => $give_id])->all();
    }

    static function russian_date($date)
    {
        $date = explode(".", $date);
        switch ($date[1]) {
            case 1:
                $m = 'января';
                break;
            case 2:
                $m = 'февраля';
                break;
            case 3:
                $m = 'марта';
                break;
            case 4:
                $m = 'апреля';
                break;
            case 5:
                $m = 'мая';
                break;
            case 6:
                $m = 'июня';
                break;
            case 7:
                $m = 'июля';
                break;
            case 8:
                $m = 'августа';
                break;
            case 9:
                $m = 'сентября';
                break;
            case 10:
                $m = 'октября';
                break;
            case 11:
                $m = 'ноября';
                break;
            case 12:
                $m = 'декабря';
                break;
        }
        return $date[0] . '&nbsp;' . $m;
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\search\UserSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    // 'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->identity->role != User::ROLE_ADMIN) {
            return $this->redirect(['/']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $all = User::find()->count();
        $completed = User::find()->where(['login_status' => 1])->count();
        $refferer = User::find()->where(['refferer_link' => 1])->count();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'all' => $all,
            'completed' => $completed,
            'refferer' => $refferer,
        ]);
    }

    public function actionSendEmail()
    {
        $users = User::find()->where(['email_status' => 0])
            ->andWhere(['login_status' => 0])->limit(50)->all();
        foreach ($users as $user) {
            $email = Yii::$app->mailer
                ->compose('success_replay', ['user' => $user])
                ->setSubject('Доступ к гивам открыт!')
                ->setTo($user->email)
                ->send();
            $user->email_status = $email;
            $user->save(false);
        }
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     */
    public function actionSuccess($id)
    {
        $model = $this->findModel($id);
        $model->status = User::STATUS_ACTIVE;
        $model->password = $this->generateRandomString();
        $model->save(false);
        Yii::$app->mailer
            ->compose('success', ['user' => $model])
            ->setSubject('Доступ к личному кабинету GiveCorp одобрен')
            ->setTo($model->email)
            ->send();
        try {
            $amo = new \AmoCRM\Client('infogivecorpru.amocrm.ru', 'info@givecorp.ru', '8d41ce120d539b58b48a874f2eb016272a069652');
            $lead = $amo->lead;
            $lead->debug(false); // Режим отладки

            $lead['name'] = $model->first_name . ' ' . $model->last_name . ' ' . $model->patronymic;
            $lead['status_id'] = time();
            $lead['tags'] = 'givecorp.ru';
            $lead['date_create'] = date('Y-m-d h:i:s');
            $lead->addCustomField(112247, $model->first_name . ' ' . $model->last_name . ' ' . $model->patronymic, 'WORK');
            $lead->addCustomField(112249, $model->phone, 'WORK');
            $lead->addCustomField(112251, $model->instagram_ak, 'WORK');
            $lead->addCustomField(112253, $model->login_status ? 'Да' : "Нет", 'WORK');
            $lead->addCustomField(112255, $model->refferer_link ? 'Да' : "Нет", 'WORK');
            $lead->addCustomField(112257, $model->email, 'WORK');
            $lead->addCustomField(112259, $model->target, 'WORK');
            $lead->apiAdd();

        } catch (\AmoCRM\Exception $e) {
            return ['error' => true, 'message' => 'Error (' . $e->getCode() . '): ' . $e->getMessage()];
        }

        return $this->redirect('/user/index');
    }

    function generateRandomString($length = 10)
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    /**
     * @param $id
     * @return \yii\web\Response
     */
    public function actionCancel($id)
    {
        $model = $this->findModel($id);
        $model->status = User::STATUS_INACTIVE;
        $model->save(false);

        return $this->redirect('/user/index');
    }

    public function actionCheckStatus()
    {
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            foreach ($post['selection'] as $id) {
                $this->sendStatus($id, isset($post['success']) ? true : false);
            }
            return $this->redirect(['/user/index', 'status' => 1]);
        }
    }

    protected function sendStatus($id, $status = false)
    {
        $user = User::findOne($id);
        $user->status = $status ? User::STATUS_ACTIVE : User::STATUS_INACTIVE;
        $user->password = $status ? $this->generateRandomString() : null;
        $user->save(false);
        if ($status) {
            Yii::$app->mailer
                ->compose('success', ['user' => $user])
                ->setSubject('Одобренно!')
                ->setTo($user->email)
                ->send();
        } else {
            Yii::$app->mailer
                ->compose('success', ['user' => $user])
                ->setSubject('Одобренно!')
                ->setTo($user->email)
                ->send();
        }

    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $user = $this->findModel($id);
        $this->findModel($id)->delete();

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'instagram_ak')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'target')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'patronymic') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'instagram_ak') ?>

    <?php // echo $form->field($model, 'target') ?>

    <?php // echo $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'role') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Создать участника');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Участники'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', isset($_GET['status']) && $_GET['status'] == 1 ? 'Заявки на консультацию' : 'Заявки на оплату');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= Html::beginForm(['user/check-status'], 'post'); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Создать участника'), ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'Заявки на консультацию'), \yii\helpers\Url::to(['/user/index', 'status' => 1]), ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Заявки на оплату'), \yii\helpers\Url::to(['/user/index', 'status' => 0]), ['class' => 'btn btn-danger']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\CheckboxColumn'],
            'first_name',
            'instagram_ak',
            'email',
            'phone',
            [
                'attribute' => 'payment_status',
                'filter' => Html::dropDownList('payment_status', $_GET['payment_status'], ['' => 'Выбрать'] + \app\models\PaymentLer::getStatusesArray()),
                'format' => 'raw',
                'value' => function (\app\models\User $model) {
                    return Html::tag('span', ucfirst(($model->payment ? $model->payment->getStatusString() : 'Не оплачен')), ['class' => $model->payment ? $model->payment->getLabelCssClassByStatus() : 'label label-danger']);
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete} {view} {success} {cancel}',
                'buttons' => [
                    'update' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-pencil"></i>', \yii\helpers\Url::to(['/user/update', 'id' => $model->id]), [
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-trash"></i>', \yii\helpers\Url::to(['/user/delete', 'id' => $model->id]), [
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]);
                    },
                    'view' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-eye-open"></i>', \yii\helpers\Url::to(['/user/view', 'id' => $model->id]), [
                        ]);
                    },
                ]
            ],
        ],
    ]); ?>
    <?= Html::submitButton('Подтвердить', ['class' => 'btn btn-primary', 'name' => 'success']); ?>
    <?= Html::submitButton('Оменить', ['class' => 'btn btn-danger', 'name' => 'cancel']); ?>
    <?= Html::endForm(); ?>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Редактирование: {name}', [
    'name' => $model->first_name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Участинки'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Редактирование');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'first_name',
            'last_name',
            'patronymic',
            'email:email',
            'instagram_ak:ntext',
            'target:ntext',
            'password',
            'role',
        ],
    ]) ?>

</div>