models/Promotion.php
<?php

namespace app\models;

use Yii;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "promotion".
 *
 * @property int $id
 * @property int $bloger_id
 * @property int $auditory
 * @property string $interest
 * @property string $count_seat
 * @property int $status
 * @property int $plus_subscriber
 * @property string $sort
 * @property float $all_cost
 * @property PromotionHasUser[] $promotionHasUsers
 * @property Blogers $bloger
 */
class Promotion extends \yii\db\ActiveRecord
{
    const STATUS_NEW = 1;
    const STATUS_END = 2;

    /**
     * {@inheritdoc}
     */
    public function statuses()
    {
        return [
            self::STATUS_NEW => 'Новый',
            self::STATUS_END => 'Закончился',
        ];
    }

    public static function tableName()
    {
        return 'promotion';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['bloger_id', 'count_seat', 'status', 'plus_subscriber', 'sort'], 'integer'],
            [['all_cost', 'auditory', 'interest'], 'safe'],
            [['bloger_id'], 'exist', 'skipOnError' => true, 'targetClass' => Blogers::className(), 'targetAttribute' => ['bloger_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'bloger_id' => 'Блогер',
            'count_seat' => 'К-тво мест',
            'status' => 'Статус',
            'plus_subscriber' => 'Накрутка(Это число + реальные подписчики)',
            'all_cost' => 'Полная цена',
            'sort' => 'Сортировка',
            'auditory' => 'Аудитория',
            'interest' => 'Интересы',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPromotionHasUsers()
    {
        return $this->hasMany(PromotionHasUser::className(), ['promotion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBloger()
    {
        return $this->hasOne(Blogers::className(), ['id' => 'bloger_id']);
    }
}

controllers/PromotionController.php
<?php

namespace app\controllers;

use app\models\Blogers;
use app\models\Promotion;
use app\models\search\PromotionSearch;
use app\models\User;
use Yii;
use app\models\Gives;
use app\models\search\GivesSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * GivesController implements the CRUD actions for Gives model.
 */
class PromotionController extends Controller
{

    /**
     * Lists all Gives models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PromotionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->identity->role != User::ROLE_ADMIN) {
            return $this->redirect(['/']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays a single Gives model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Gives model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Promotion();

        if ($model->load(Yii::$app->request->post())) {
            $model->status = Gives::STATUS_NEW;
            if ($file = UploadedFile::getInstance($model, 'image')) {
                $dir = Yii::getAlias('@webroot/img/');
                $fname = uniqid("", true) . '.' . $file->extension;
                $model->image = $fname;
                $file->saveAs($dir . $fname);
            }
            $promotion = Promotion::find()->max('sort');
            if ($promotion) {
                $model->sort = $promotion + 1;
            } else {
                $model->sort = 0;
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            };
        }

        return $this->render('create', [
            'model' => $model,
            'blogers' => $this->getBlogers()
        ]);
    }

    protected function getBlogers()
    {
        return ArrayHelper::map(Blogers::find()->all(), 'id', 'name');
    }

    /**
     * Updates an existing Gives model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'blogers' => $this->getBlogers()
        ]);
    }

    public function actionNew($id)
    {
        $model = $this->findModel($id);
        $model->status = Promotion::STATUS_NEW;
        $model->save(false);

        return $this->redirect('/gives/index');
    }

    public function actionFinish($id)
    {
        $model = $this->findModel($id);
        $model->status = Promotion::STATUS_END;
        $model->save(false);
        return $this->redirect('/gives/index');
    }

    /**
     * Deletes an existing Gives model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Gives model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Promotion the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Promotion::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/promotion/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Gives */
/* @var $form yii\widgets\ActiveForm */
/* @var $blogers \app\models\Blogers[] */

?>

<div class="gives-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'bloger_id')->widget(\kartik\select2\Select2::classname(), [
        'data' => $blogers,
        'language' => 'ru',
        'options' => ['placeholder' => 'Выбрать блогера'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>
    <?= $form->field($model, 'all_cost')->textInput() ?>
    <span>Аудитория</span>
    <?= $form->field($model, 'auditory', [
        'template' => "<div>{input}\n<div class=\"error\">{error}</div></div>",
    ])->widget(\zxbodya\yii2\tinymce\TinyMce::className(), [
        'options' => ['rows' => 15],
        'language' => 'ru',
//        'spellcheckerUrl'=>'http://speller.yandex.net/services/tinyspell',
        'fileManager' => [
            'class' => \zxbodya\yii2\elfinder\TinyMceElFinder::className(),
            'connectorRoute' => 'el-finder/connector',
        ],
    ]); ?>
    <?php
    if (!$model->isNewRecord) {
        echo $form->field($model, 'sort')->textInput();
    }
    ?>
    <?= $form->field($model, 'interest')->textInput() ?>
    <?= $form->field($model, 'count_seat')->textInput() ?>
    <?= $form->field($model, 'plus_subscriber')->textInput() ?>


    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/promotion/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\GivesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gives-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'bloger_id') ?>

    <?= $form->field($model, 'count_sub') ?>

    <?= $form->field($model, 'date_start') ?>

    <?= $form->field($model, 'date_end') ?>

    <?php // echo $form->field($model, 'count_seats') ?>

    <?php // echo $form->field($model, 'cost') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/promotion/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Gives */
/* @var $blogers \app\models\Blogers[] */

$this->title = Yii::t('app', 'Создание рекламы');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Реклама'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gives-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'blogers' => $blogers
    ]) ?>

</div>

views/promotion/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\GivesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Реклама');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gives-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Создать рекламу'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'bloger_id',
                'value' => function (\app\models\Promotion $model) {
                    return $model->bloger->name;
                }
            ],
            [
                'attribute' => 'status',
                'value' => function (\app\models\Promotion $model) {
                    return $model->statuses()[$model->status];
                }
            ],
            'auditory',
            'interest',
            'count_seat',
            'plus_subscriber',
            'all_cost',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete} {view} {new} {finish}',
                'buttons' => [
                    'update' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-pencil"></i>', \yii\helpers\Url::to(['/promotion/update', 'id' => $model->id]), [
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-trash"></i>', \yii\helpers\Url::to(['/promotion/delete', 'id' => $model->id]), [
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]);
                    },
                    'view' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-eye-open"></i>', \yii\helpers\Url::to(['/promotion/view', 'id' => $model->id]), [
                        ]);
                    },
                    'new' => function ($url, $model) {
                        return Html::a('<i title="Новый" class="glyphicon glyphicon-ok"></i>', \yii\helpers\Url::to(['/promotion/new', 'id' => $model->id]), [
                        ]);
                    },
                    'finish' => function ($url, $model) {
                        return Html::a('<i title="Закончить" class="glyphicon glyphicon-remove"></i>', \yii\helpers\Url::to(['/promotion/finish', 'id' => $model->id]), [
                        ]);
                    }
                ]
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/promotion/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Gives */
/* @var $blogers \app\models\Blogers[] */

$this->title = Yii::t('app', 'Редактирование рекламы  {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Реклама'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Редактирование');
?>
<div class="gives-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'blogers' => $blogers
        ,
    ]) ?>

</div>

views/promotion/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Promotion */

$this->title = 'Реклама ИД ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Promotion'), 'url' => ['index']];
\yii\web\YiiAsset::register($this);
?>
<div class="gives-view">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'bloger_id',
                'value' => function (\app\models\Promotion $model) {
                    return $model->bloger->instagram_name;
                }
            ],
            [
                'attribute' => 'status',
                'value' => function (\app\models\Promotion $model) {
                    return $model->statuses()[$model->status];
                }
            ],

            'auditory',
            'interest',
            'count_seat',
            'plus_subscriber',
            'all_cost',
        ],
    ]) ?>

    <?php
    $dataProvider = new \yii\data\ActiveDataProvider([
        'query' => $model->getPromotionHasUsers(),
        'pagination' => [
            'pageSize' => 20,
        ],
    ]);

    ?>
    <div><h2>Участвуют в данной Рекламе</h2></div>
    <?= \yii\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'user.first_name',
            'user.last_name',
            'user.email',
            'user.instagram_ak',
            'user.phone',

            //  ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>