controllers/MainController.php
<?php

namespace app\controllers;

use alexandernst\devicedetect\DeviceDetect;
use app\models\Blogers;
use app\models\GiveHasUser;
use app\models\Gives;
use app\models\LoginForm;
use app\models\PaymentLer;
use app\models\PaymentSpecial;
use app\models\Promotion;
use app\models\User;
use app\services\payment\PaymentFactory;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * MainController implements the CRUD actions for User model.
 */
class MainController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = 'user';
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionPrePay()
    {
        return $this->render('pre-pay');
    }


    public function actionPromotion($cost = false, $count_seat = false, $limit = 4)
    {
        /**
         * @var $detect DeviceDetect
         */
        $detect = Yii::$app->devicedetect;

        $promotions = Promotion::find()->where(['status' => Gives::STATUS_NEW]);
        if ($cost) {
            $promotions->orderBy('all_cost ' . $cost);
        }
        if ($count_seat) {
            $promotions->orderBy('count_seat ' . $count_seat);
        }
        if (!$cost && !$count_seat) {
            $promotions->orderBy(['sort' => SORT_ASC]);
        }
        $blogers = Blogers::find()->where(['is_star_promotion' => true])->with('promotion')->orderBy('id DESC');
        $count = $blogers->all();
        if ($detect->isMobile()) {
            $blogers->limit($limit);
        }

        $display = true;
        if (count($count) <= $limit) {
            $display = false;
        }

        return $this->render('promotion', ['promotions' => $promotions->all(), 'blogers' => $blogers->all(), 'display' => $display, 'limit' => $limit]);
    }

    /**
     * @return string
     *
     */
    public function actionIndex()
    {
        /**
         * @var $detect DeviceDetect
         */
        $gives = Gives::find()->where(['status' => Gives::STATUS_NEW])->orderBy(['sort' => SORT_ASC])->all();
        return $this->render('index_test',
            [
                'gives' => $gives,
            ]
        );
    }

    /**
     * @param int $limit
     * @param int $limit_give
     * @return string
     */
    public function actionIndexTest($limit = 4, $limit_give = 5)
    {
        /**
         * @var $detect DeviceDetect
         */
        $detect = Yii::$app->devicedetect;
        $blogers = Blogers::find()->where(['is_star' => true])->orderBy('id DESC');
        if ($detect->isMobile()) {
            $blogers->limit($limit);
        }
        $blogers = $blogers->all();
        $display = true;
        $display_give = true;
        if (count($blogers) != $limit) {
            $display = false;
        }

        if (isset($_GET['open']) && $_GET['open'] == 1) {
            $user = User::find()->where(['email' => $_GET['email']])->one();
            if ($user) {
                $user->refferer_link = 1;
                $user->save(false);
            }
        }
        $top_give = Gives::findOne(['is_top' => true, 'status' => Gives::STATUS_NEW]);
        $main_give = Gives::findOne(['is_main' => true, 'status' => Gives::STATUS_NEW]);
        $hot_give = Gives::findOne(['is_hot' => true, 'status' => Gives::STATUS_NEW]);
        $gives = Gives::find()->limit($limit_give)->where(['is_main' => false])->andWhere(['status' => Gives::STATUS_NEW])->orderBy(['sort' => SORT_ASC])->all();
        if (count($gives) != $limit_give) {
            $display_give = false;
        }
        return $this->render('index_test',
            [
                'blogers' => $blogers,
                'top_give' => $top_give,
                'hot_give' => $hot_give,
                'main_give' => $main_give,
                'gives' => $gives,
                'limit' => $limit,
                'limit_give' => $limit_give,
                'display' => $display,
                'display_give' => $display_give,
            ]
        );
    }

    public function actionGives($date = false, $cost = false, $bloger = false)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['/main/index', 'open' => 1, 'email' => $_GET['email']]));
        }
        $gives = Gives::find()->where(['status' => Gives::STATUS_NEW]);
        $gives->andWhere(['is_main' => false]);
        if (!$date) {
            $gives->orderBy(['sort' => SORT_ASC]);
        }
        if ($bloger) {
            $gives->andWhere(['bloger_id' => $bloger]);
        }
        if ($date) {
            $gives->orderBy('date_start ' . $date);
        }
        if ($cost) {
            $gives->orderBy('all_cost ' . $cost);
        }

        return $this->render('gives', ['gives' => $gives->all()]);
    }

    public function actionBlogers()
    {
        return $this->render('blogers');
    }

    public function actionTelegramSee()
    {
        /**
         * @var $user User
         */
        $user = Yii::$app->user->identity;
        $user->telegramm_see = 1;
        $user->save(false);
    }

    public function actionAmoCRM()
    {
        /**
         * @var $user User
         */
        try {
            $amo = new \AmoCRM\Client('infogivecorpru.amocrm.ru', 'info@givecorp.ru', '8d41ce120d539b58b48a874f2eb016272a069652');
            $user = Yii::$app->user->identity;
            $lead = $amo->lead;
            $lead->debug(false); // Режим отладки

            $lead['name'] = $user->target;
            $lead['status_id'] = time();
            $lead['tags'] = 'givecorp.ru';
            $lead['date_create'] = date('Y-m-d h:i:s');
            $lead->addCustomField(112247, $user->first_name . ' ' . $user->last_name . ' ' . $user->patronymic, 'WORK');
            $lead->addCustomField(112249, $user->phone, 'WORK');
            $lead->addCustomField(112251, $user->instagram_ak, 'WORK');
            $lead->addCustomField(112253, $user->login_status ? 'Да' : "Нет", 'WORK');
            $lead->addCustomField(112255, $user->refferer_link ? 'Да' : "Нет", 'WORK');
            $lead->addCustomField(112257, $user->email, 'WORK');
            $lead->addCustomField(112259, $user->target, 'WORK');
            $lead->apiAdd();

        } catch (\AmoCRM\Exception $e) {
            return ['error' => true, 'message' => 'Error (' . $e->getCode() . '): ' . $e->getMessage()];
        }
    }

    public function actionGivesCompleted($date = false, $cost = false, $bloger = false, $limit = 3)
    {
        $gives = Gives::find()->where(['status' => Gives::STATUS_END])->limit($limit);
        if ($bloger) {
            $gives->andWhere(['bloger_id' => $bloger]);
        }
        if ($date) {
            $gives->orderBy('date_start ' . $date);
        }
        if ($cost) {
            $gives->orderBy('cost ' . $cost);
        }
        $bloger = Blogers::findOne($bloger);
        $gives = $gives->all();
        $display = true;
        if (count($gives) != $limit) {
            $display = false;
        }

        return $this->render('gives_completed',
            [
                'date' => $date,
                'gives' => $gives,
                'bloger' => $bloger,
                'cost' => $cost,
                'display' => $display,
                'limit' => $limit
            ]
        );
    }

    public function actionBuyGive($id)
    {
        $GHU = new GiveHasUser();
        $GHU->give_id = $id;
        $GHU->user_id = Yii::$app->user->id;
        $GHU->save(false);
        Yii::$app->mailer
            ->compose('success_pay')
            ->setSubject('Успешная оплата')
            ->setTo('info@givecorp.ru')
            ->send();

        return $this->redirect('/main/thank-page');
    }

    public function actionThankPage()
    {
        return $this->render('thank-page');
    }

    public function actionLogin()
    {

        $model = new LoginForm();
        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post())) {
                if ($model->login()) {
                    if (Yii::$app->user->identity->role == User::ROLE_ADMIN) {
                        return $this->redirect(Url::to(['/user/index', 'status' => 1]));
                    }
                    $user = User::findOne(Yii::$app->user->id);
                    if ($user) {
                        $user->login_status = 1;
                        $user->login_date = date('Y-m-d H:i:s');
                        $user->save(false);
                    }
                    return $this->redirect(Url::to(['/main/gives']));
                } else {
                    Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
                    return \yii\widgets\ActiveForm::validate($model);
                }
            }
        }
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['user/index']);
        }
        return $this->render('login', ['model' => $model]);
    }

    public function actionRecoveryPassword()
    {
        $user = User::findOne(['email' => Yii::$app->request->post('User')['email']]);
        if ($user) {
            $user->password = Yii::$app->security->generateRandomString(10);
            if ($user->save(false)) {
                Yii::$app->mailer
                    ->compose('recovery', ['user' => $user])
                    ->setSubject('Ваш новый пароль')
                    ->setTo($user->email)
                    ->send();
            }
        } else {

views/blocks/header.php
<header class="<?=$header_transparent?>">
    <div class="wrapper">
        <div class="header"><a class="header_logo logo logo_black" href="/">givecorp</a>
            <div class="header_button"><a class="button button_transparent_blue <?= Yii::$app->user->identity->role == \app\models\User::ROLE_ADMIN ? '' : 'getconsultation_opener' ?>" href="<?= Yii::$app->user->identity->role == \app\models\User::ROLE_ADMIN ? \yii\helpers\Url::to('/gives') : '#' ?>">
                    <?= Yii::$app->user->identity->role == \app\models\User::ROLE_ADMIN ? 'В админку' : 'Получить консультацию' ?></a>
            </div>
            <div class="header_right"><a class="header_login <?= Yii::$app->user->isGuest ? 'login_opener' : '' ?>"
                                         href="<?= Yii::$app->user->isGuest ? '#' : \yii\helpers\Url::to(['/site/logout']) ?>"><?= Yii::$app->user->isGuest ? 'Войти' : 'Выйти' ?></a><a
                        class="header_menu menu_opener" href="#"><span></span><span
                            class="header_menu_middle"></span><span></span></a></div>
        </div>
    </div>
</header>

views/blocks/table_popup.php
<?php
/**
 * @var $give \app\models\Gives
 */
?>
<div class="table_popup table_popup_top table_popup_bloger"><span
            class="table_popup_close"><svg
                viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" fill="rgb(77, 115, 215)"
                                                  d="M15.810,1.103 L8.913,7.999 L15.810,14.896 C16.062,15.149 16.062,15.558 15.810,15.810 C15.684,15.937 15.518,16.000 15.353,16.000 C15.188,16.000 15.022,15.937 14.896,15.810 L7.999,8.913 L1.103,15.810 C0.977,15.937 0.811,16.000 0.646,16.000 C0.480,16.000 0.315,15.937 0.189,15.810 C-0.064,15.558 -0.064,15.149 0.189,14.896 L7.085,7.999 L0.189,1.103 C-0.064,0.850 -0.064,0.441 0.189,0.188 C0.441,-0.064 0.850,-0.064 1.103,0.188 L7.999,7.085 L14.896,0.188 C15.148,-0.064 15.558,-0.064 15.810,0.188 C16.062,0.441 16.062,0.850 15.810,1.103 Z"></path>
                                        </svg></span>
    <div class="table_popup_bloger_photo"
         style="background-image: url(/img/<?= $give->bloger->avatar ?>)"></div>
    <div class="table_popup_bloger_name"><?= $give->bloger->name ?></div>
    <?php
    $arr = null;
    $arr2 = null;
    if (stristr($give->bloger->instagram, ',')) {
        $arr = explode(',', $give->bloger->instagram);
        $arr2 = explode(',', $give->bloger->instagram_name);
    }
    if ($arr != null) {
        ?>
        <div style="display: inline-flex">
            <a class="table_popup_bloger_inst" href="<?= $arr[0] ?>"><?= $arr2[0] ?></a>
            <span class="plus">&nbsp;+&nbsp;</span>
            <a class="table_popup_bloger_inst" href="<?= $arr[1] ?>"><?= $arr2[1] ?></a>
        </div>
        <?php
        if (isset($arr[2])) {
            ?>
            <div style="display: inline-flex">
                <a class="table_popup_bloger_inst" href="<?= $arr[2] ?>"><?= $arr2[2] ?></a>
                <span class="plus">&nbsp;+&nbsp;</span>
                <a class="table_popup_bloger_inst" href="<?= $arr[3] ?>"><?= $arr2[3] ?></a>
            </div>
            <?php
        }
    } else {
        ?>
        <a class="table_popup_bloger_inst"
           href="<?= $give->bloger->instagram ?>"><?= $give->bloger->instagram_name ?></a>
        <?php
    }
    ?>
    <div class="table_popup_bloger_sub"><?= $give->bloger->count_subscribes ?>
        подписчиков
    </div>
    <div class="table_popup_bloger_text"><?= $give->bloger->text ?>
    </div>
    <!-- <a class="table_popup_bloger_link"
       href="<? /*= \yii\helpers\Url::to(Yii::$app->user->isGuest ? '/main/registration' : ['/main/gives-completed', 'bloger' => $give->bloger_id]) */ ?>">Проведенные
        гивы</a>-->
    <div class="table_popup_bloger_bottom">
        <div class="table_popup_bloger_bottom_next">Следующий
            гив: с <?= \app\models\User::russian_date(date('d.m.Y', strtotime($give->date_start))) ?><br>
            по <?= \app\models\User::russian_date(date('d.m.Y', strtotime($give->date_end))) ?></div>
        <div class="table_popup_bloger_bottom_cost">
                                        <span>Мест: <?= trim(($give->plus_subscriber ? count($give->giveHasUsers) + $give->plus_subscriber : count($give->giveHasUsers))) ?>
                                            /<?= $give->count_seats ?></span>
            <?php
            if (Yii::$app->user->isGuest && Yii::$app->controller->action->id != 'index-test') {
                ?>
                <a onclick="ym(53344498, 'reachGoal', 'subscribe'); return true;"
                   style="margin-right: 0" class="section_givs_cost_getprice"
                   href="<?= \yii\helpers\Url::to('main/registration') ?>"><?= 'Узнать цену' ?></a>
                <?php
            } else {
                ?>
                <span>Стоимость: <?= $give->all_cost ?>руб.</span>
                <?php
            }
            ?>
        </div>
        <?php
        if (Yii::$app->controller->action->id == 'index-test') {
            ?>
            <a onclick="ym(53344498, 'reachGoal', <?= Yii::$app->controller->action->id == 'index' ? 'subscribe' : 'join' ?>); return true;"
               class="link"
               href="<?= \yii\helpers\Url::to(['/main/pre-pay', 'cost' => $give->all_cost, 'give_id' => $give->id]) ?>">Участвовать</a>
            <?php
        } else {
            ?>
            <a onclick="ym(53344498, 'reachGoal', <?= Yii::$app->controller->action->id == 'index' ? 'subscribe' : 'join' ?>); return true;"
               class="link"
               href="<?= $url_custom ? $url_custom : (Yii::$app->user->isGuest ? '/main/registration' : '/main/gives') ?>"><?= $text_custom ? $text_custom : 'Участвовать' ?></a>
            <?php
        }
        ?>
    </div>
</div>